sudo: required

language: sh

services:
  - docker

before_install:
  - docker pull nlknguyen/alpine-shellcheck
  - docker build -t nlknguyen/papercolor-vim-precompiler:base base/
  - docker build -t nlknguyen/papercolor-vim-precompiler:app app/

script:
  - docker run --rm -it -v $(pwd):/mnt nlknguyen/alpine-shellcheck app/run.sh
