sudo: required

language: sh

services:
  - docker

before_install:
  - shopt -s expand_aliases  # allow alias
  - shopt -s globstar  # allow use of **

install:
  - docker pull nlknguyen/alpine-shellcheck
  - alias shellcheck='docker run --rm -it -v $(pwd):/mnt nlknguyen/alpine-shellcheck'

script:
  - shellcheck --version
  - shellcheck **/*.sh
  - docker build -t nlknguyen/papercolor-vim-precompiler:base base/
  - docker build -t nlknguyen/papercolor-vim-precompiler:latest .

